// Generated by JavaCPP version 1.5.3: DO NOT EDIT THIS FILE

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback1(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback2(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback3(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback4(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback5(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback6(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback7(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback8(std::basic_string< char >& arg0);
JNIIMPORT const char* JavaCPP_api_ApiClient_00024Client_allocate_callback9(std::basic_string< char >& arg0);
JNIIMPORT const char* call(std::basic_string< char >& arg0);
JNIIMPORT const char* call1(std::basic_string< char >& arg0);
JNIIMPORT const char* call2(std::basic_string< char >& arg0);
JNIIMPORT const char* call3(std::basic_string< char >& arg0);
JNIIMPORT const char* call4(std::basic_string< char >& arg0);
JNIIMPORT const char* call5(std::basic_string< char >& arg0);
JNIIMPORT const char* call6(std::basic_string< char >& arg0);
JNIIMPORT const char* call7(std::basic_string< char >& arg0);
JNIIMPORT const char* call8(std::basic_string< char >& arg0);
JNIIMPORT const char* call9(std::basic_string< char >& arg0);
#ifdef __cplusplus
}
#endif
